[FIX] fix bash sirius linux format

diff --git a/Linux/64bit/Sirius/sirius b/Linux/64bit/Sirius/sirius
--- a/Linux/64bit/Sirius/sirius
+++ b/Linux/64bit/Sirius/sirius
@@ -74,7 +74,10 @@ _canonicalize_file_path() {
 # Assumes that the lib dir is in the same directory as this script
 LIB_DIR="$(dirname $(realpath $0))/lib"
 # Set APP_HOME based on path to sirius (realpath)
-APP_HOME="$(dirname $(realpath $0))
+APP_HOME="$(dirname $(realpath $0))"
+
+echo "lib_dir" $LIB_DIR
+echo "app_home" $APP_HOME
 
 export LD_LIBRARY_PATH="$GUROBI_HOME/lib:$APP_HOME/lib:$LD_LIBRARY_PATH"
 export DYLD_LIBRARY_PATH="$LD_LIBRARY_PATH"
@@ -127,17 +130,11 @@ if [ -n "$JAVA_HOME" ] ; then
         JAVACMD="$JAVA_HOME/bin/java"
     fi
     if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
     fi
 else
     JAVACMD="java"
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
-
-Please set the JAVA_HOME variable in your environment to match the
-location of your Java installation."
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
 fi
 
 # Increase the maximum file descriptors if we can.
