[UPDATE] Sirius 4.0 (build 10) [EDIT] bash script

diff --git a/Linux/64bit/Sirius/sirius b/Linux/64bit/Sirius/sirius
--- a/Linux/64bit/Sirius/sirius
+++ b/Linux/64bit/Sirius/sirius
@@ -22,32 +22,32 @@ DEFAULT_JVM_OPTS="-Djava.library.path=\"$GUROBI_HOME/lib:$CPLEX_HOME/lib:$APP_HO
 MAX_FD="maximum"
 
 warn ( ) {
-    echo "$*"
+   echo "$*"
 }
 
 die ( ) {
-    echo
-    echo "$*"
-    echo
-    exit 1
+   echo
+   echo "$*"
+   echo
+   exit 1
 }
 
 CLASSPATH="${LIB_DIR}/*:$APP_HOME/../../../All/Sirius/lib/*:${GUROBI_HOME}/lib/gurobi.jar:${CPLEX_HOME}/lib/cplex.jar"
 
 # Determine the Java command to use to start the JVM.
 if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-        # IBM's JDK on AIX uses strange locations for the executables
-        JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-        JAVACMD="$JAVA_HOME/bin/java"
-    fi
-    if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
-    fi
+   if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+       # IBM's JDK on AIX uses strange locations for the executables
+       JAVACMD="$JAVA_HOME/jre/sh/java"
+   else
+       JAVACMD="$JAVA_HOME/bin/java"
+   fi
+   if [ ! -x "$JAVACMD" ] ; then
+       die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
+   fi
 else
-    JAVACMD="/usr/bin/java"
-    #which $JAVACMD >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
+   JAVACMD="/usr/bin/java"
+   #which $JAVACMD >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
 fi
 
 # Escape application args
@@ -63,8 +63,7 @@ eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $SIRIUS_OPTS -classpath "\"$CLASSPATH\"
 
 # by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
 if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
-  cd "$(dirname "$0")"
+ cd "$(dirname "$0")"
 fi
 
 exec "$JAVACMD" "$@"
-
